### ISSUE TITLE
Crash when update on Android 14 

### ISSUE THREAD

**Issue by dungdinhmanh** [maxrave-dev/SimpMusic#477]
**Describe the bug**
Crash when update to 0.2.3 version on Android 14 HMD Global Nokia 6.1 Plus 

**Log (Error Details)**
Build version: 0.2.3 
Current date: 2024-08-08 21:35:12 
Device: HMD Global Nokia 6.1 Plus 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.NoSuchMethodError: No interface method removeLast()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
	at U6.d.a(Unknown Source:0)
	at U6.e.parseNewRelease(Unknown Source:339)
	at W6.P.invokeSuspend(Unknown Source:94)
	at k9.a.resumeWith(Unknown Source:11)
	at Oa.g0.run(Unknown Source:130)
	at Ua.n.run(Unknown Source:3)
	at Wa.n.run(Unknown Source:2)
	at Wa.d.runSafely(Unknown Source:0)
	at Wa.b.run(Unknown Source:64)
	Suppressed: Ua.j: [p1{Cancelling}@9acea37, Dispatchers.Main.immediate]

User actions: 
2024-08-08 21:35:06: MainActivity created
2024-08-08 21:35:06: MainActivity resumed
